# Generated by Django 4.0.5 on 2022-07-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_rename_receta_7a10_receta_delete_receta_1a3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='ingrediente_1',
            new_name='ing_y_cant',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='ingrediente_10',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_1',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_10',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_2',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_3',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_4',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_5',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_6',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_7',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_8',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_9',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente_2',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente_3',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente_4',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente_5',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente_6',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente_7',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente_8',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente_9',
        ),
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta',
            name='procedimiento',
            field=models.CharField(max_length=30),
        ),
    ]
