# Generated by Django 4.0.5 on 2022-07-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_rename_ingrediente_1_receta_ing_y_cant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receta'),
        ),
        migrations.AddField(
            model_name='receta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
